server:
  port: 8091
  servlet:
    session:
      cookie:
        name: CLIENTSESSION
spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          first-client:
            client-id: test_client
            client-secret: client_password
            client-name: first-client
            scope: resource:read
            provider: custom-provider
            redirect-uri: "{baseUrl}/login/oauth2/code/first-client"
            #client-authentication-method: basic
            authorization-grant-type: authorization_code
        provider:
          custom-provider:
            token-uri: http://localhost:8090/oauth/token
            authorization-uri: http://localhost:8090/oauth/authorize
            user-info-uri: http://localhost:8090/api/users/me
            user-name-attribute: name
